version: '3.8'

services:
  localstack:
    image: localstack/localstack:2.0.0
    container_name: whisper-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EAGER_SERVICE_LOADING=1
      - WAIT_FOR_INIT_SCRIPTS=1
      - DISABLE_CORS_CHECKS=1
      - DISABLE_CUSTOM_CORS_S3=1
      - DISABLE_CORS_HEADERS=0
      - EXTRA_CORS_ALLOWED_ORIGINS=http://localhost:5173
      - EXTRA_CORS_ALLOWED_HEADERS=*
      - EXTRA_CORS_EXPOSED_HEADERS=ETag,Content-Length,Content-Type
    volumes:
      - ./localstack-init:/etc/localstack/init/ready.d
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - whisper-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  whisper-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whisper-app
    restart: on-failure
    volumes:
      - ./src:/app/src
      - ./downloads:/app/downloads
      - ./processed:/app/processed
      - ./start-app.sh:/app/start-app.sh
    environment:
      - ENVIRONMENT=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - S3_BUCKET_NAME=whisperprocessing-files
      - WHISPER_QUEUE_URL=http://localstack:4566/000000000000/whisperprocessing-whisper-jobs
      - AWS_ENDPOINT_URL=http://localstack:4566
      - SQS_ENDPOINT=http://localstack:4566
      - S3_ENDPOINT=http://localstack:4566
      - DEBUG=1
      - AWS_CLI_AUTO_PROMPT=on-partial
    depends_on:
      localstack:
        condition: service_healthy
    networks:
      - whisper-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  service-info:
    image: curlimages/curl:latest
    container_name: whisper-info
    depends_on:
      localstack:
        condition: service_healthy
    command: |
      sh -c "
        echo '================================================================'
        echo '                 SERVICE INFORMATION FOR INTEGRATION            '
        echo '================================================================'
        echo 'S3 Bucket URL: http://localhost:4566/whisperprocessing-files'
        echo 'SQS Queue URL: http://localhost:4566/000000000000/whisperprocessing-whisper-jobs'
        echo '================================================================'
        echo 'Environment variables for API and UI projects:'
        echo 'AWS_ENDPOINT_URL=http://localhost:4566'
        echo 'AWS_REGION=us-east-1'
        echo 'AWS_ACCESS_KEY_ID=test'
        echo 'AWS_SECRET_ACCESS_KEY=test'
        echo 'S3_BUCKET_NAME=whisperprocessing-files'
        echo 'WHISPER_QUEUE_URL=http://localhost:4566/000000000000/whisperprocessing-whisper-jobs'
        echo '================================================================'
      "
    networks:
      - whisper-network

networks:
  whisper-network:
    driver: bridge 